# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          - task: UniversalPackages@0
            inputs:
              command: 'download'
              downloadDirectory: '$(System.DefaultWorkingDirectory)'
              feedsToUse: 'internal'
              vstsFeed: '92298d75-05de-4959-92e7-38a3c6bc5756/61a66d17-4a18-473d-ad30-008c2d2dcfb6'
              vstsFeedPackage: '22b968ca-5844-47ef-8a39-dc7d78a802e0'
              vstsPackageVersion: '19.11.0'
              - task: CmdLine@2
                inputs:
                  script: |
                    sudo mv $(System.DefaultWorkingDirectory)/twistcli /usr/bin/twistcli
                    sudo chmod +x /usr/bin/twistcli
                    - task: twistcli-scan@1
                      inputs:
                        scanType: 'images'
                        twistlockService: 'SC1'
                        vulnerabilityThreshold: 'low'
                        onlyFixed: false
                        gracePeriod: '0'
                        complianceThreshold: 'low'
                        artifact: 'k8-demo'